# Generated by Django 5.2.3 on 2025-07-04 15:46

import applications.oaauth.models
import django.db.models.deletion
import django.utils.timezone
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('uid', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=8, max_length=8, prefix='', primary_key=True, serialize=False, verbose_name='用户ID')),
                ('realname', models.CharField(max_length=50, verbose_name='真实姓名')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号')),
                ('is_staff', models.BooleanField(default=False, verbose_name='职员状态')),
                ('status', models.IntegerField(choices=[(1, '已激活'), (2, '未激活'), (3, '已锁定')], default=2, verbose_name='用户状态')),
                ('is_active', models.BooleanField(default=True, verbose_name='激活状态')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='加入日期')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '员工',
                'verbose_name_plural': '员工',
            },
            managers=[
                ('objects', applications.oaauth.models.OAUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='OADepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='部门名称')),
                ('intro', models.CharField(blank=True, max_length=200, null=True, verbose_name='部门简介')),
                ('leader', models.CharField(blank=True, max_length=100, null=True, verbose_name='部门主管(Leader)')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_of_departments', to=settings.AUTH_USER_MODEL, verbose_name='上级分管(Manager)')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
            },
        ),
        migrations.AddField(
            model_name='oauser',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staffs', to='oaauth.oadepartment', verbose_name='所属部门'),
        ),
    ]
